name: CI/CD for React Native App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4
    
      # Bước 2: Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'  # Thay đổi theo phiên bản Node.js của bạn
    
      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install
    
      # Bước 4: Chạy các bài test
      - name: Run tests
        run: npm test

  build-android-ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Thiết lập Java và Android SDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          java-version: '17'

      
      # Bước 5: Xây dựng ứng dụng Android
      - name: Build Android app (Ubuntu)
        run: |
          cd android
          ./gradlew assembleRelease

  build-android-macos:
    runs-on: macos-latest
    needs: build-android-ubuntu  # Đảm bảo công việc này chạy sau khi build trên Ubuntu

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Thiết lập CocoaPods cho iOS (nếu cần thiết cho việc build Android trên macOS)
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      # Bước 5: Xây dựng ứng dụng Android trên macOS
      - name: Build Android app (macOS)
        run: |
          cd android
          ./gradlew assembleRelease
