name: ReactNative CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        # Bước 1: Check out code từ repository
        - name: Checkout code
          uses: actions/checkout@v4
    
        # Bước 2: Thiết lập Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '16' # Điều chỉnh phiên bản Node.js theo dự án
    
        # Bước 3: Cài đặt dependencies
        - name: Install dependencies
          run: npm install
    
        # Bước 4: Chạy test
        - name: Run tests
          run: npm test

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Sử dụng Node.js mới nhất phù hợp với React Native

      - name: Install dependencies
        run: npm install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          api-level: 31
          build-tools: 31.0.0

      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Authenticate with Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-key.json
          gcloud auth activate-service-account --key-file=$HOME/firebase-key.json
          gcloud --quiet config set project your-firebase-project-id

      - name: Run tests on Firebase Test Lab
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --app android/app/build/outputs/apk/release/app-release.apk \
            --device model=Pixel3,version=31,locale=en,orientation=portrait \
            --timeout 15m \
            --results-dir=results

      - name: Upload Firebase Test Lab results
        uses: actions/upload-artifact@v4
        with:
          name: firebase-test-results
          path: results/

  build-ios:
    runs-on: macos-latest
    needs: build-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Build iOS app
        run: |
          xcodebuild \
            -workspace ios/YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/YourApp.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/YourApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $PWD/build

      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/*.ipa
